version: '3.8'

services:
  sveltekit:
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV}
      - SERVER_PORT=${SERVER_PORT}
      - PORT=${SERVER_PORT}
      - HOST=0.0.0.0
    networks:
      - husky
networks:
    husky:
        driver: bridge
